- hosts: all
  become: true
  tasks: 
  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: ./kaizen 
      dest: /tmp
      remote_src: yes

  - name: create file 
    ansible.builtin.shell: touch hello 
  